name = "Blocky Gates"
author = "Iggy S. Aurus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74de5e0d898af6b386b7c73de87f3fbf40a5f6e2dd79460836f7bc068dfab5cf"

[versions]
minecraft = "1.19.2"
quilt = "0.20.2"
