name = "Blocky Gates"
author = "Iggy S. Aurus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e33c1ebdf726d7da3a4120dcf2499691b32770fc813f7d22f45c9e486eafeeb8"

[versions]
minecraft = "1.19.2"
quilt = "0.20.2"
