name = "Blocky Gates"
author = "Iggy S. Aurus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a448c1de1b3003b5e05c969f2af782cd518c19e456dc12a63a56f3dd6c9a4833"

[versions]
minecraft = "1.19.2"
quilt = "0.20.2"
