name = "Blocky Gates"
author = "Iggy S. Aurus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "664e90d14904c77b2b20416155826ab72c3531abf912d9cd47bce6f886cd7d2f"

[versions]
minecraft = "1.19.2"
quilt = "0.20.2"
